/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dutrabot

import dutrabot.helpers.mapQuestions
import dutrabot.helpers.startBot

/**
 * Função responsável por inicializar a aplicação
 *
 * @param args Argumentos de inicialização
 */
fun main(args: Array<String>) {
    // verifica por argumento map na primeira posição
    if (args.isNotEmpty() && args[0] == "map") { // caso seja passado é executado script de mapeamento
        println("Mapping questions...")
        mapQuestions()
        println("Done!")
    } else { // caso não encontre o argumento map, é iniciado a aplicação robô
        println("Stating app...")
        startBot()
        println("Done!")
    }
}
