/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dutrabot

import dutrabot.helpers.mapQuestions
import dutrabot.helpers.startBot


fun main(args: Array<String>) {
    if (args.isNotEmpty() && args[0] == "map") {
        println("Mapping questions...")
        mapQuestions()
        println("Done!")
    } else {
        println("Stating app...")
        startBot()
        println("Done!")
    }
}
